posts from database
Agent007little/Django_project pull request #10
Opened 2024-03-18 18:38 UTC by Agent007little

Сделал отображение постов из базы данных. Пока тестовый вариант.

2024-03-19 09:06 UTC, burtovoy requested changes

2024-03-19 09:06 UTC, burtovoy commented on django_project/settings.py
>      'default': {
Почему здесь изменилось?

2024-03-19 12:24 UTC, Agent007little commented on django_project/settings.py
>      'default': {
Тестировал на локальной базе данных, забыл сменить

2024-03-19 16:20 UTC, Agent007little commented
Доделал отображение фоток в сообщениях. Выложил на сервер.

2024-03-20 16:39 UTC, burtovoy commented on django_project/settings.py
>      'default': {
Ты же настроил что, чтобы через переменные окружения работало? Не должно быть такого что нужно менять

2024-04-08 17:26 UTC, merged