Main page
Agent007little/Django_project pull request #4
Opened 2024-02-03 18:30 UTC by Agent007little

Создал главную страницу для мобильной версии

2024-02-05 08:58 UTC, burtovoy requested changes
Почем не получается на сайт зайти. Задеплоено?

2024-02-05 09:00 UTC, Agent007little commented
Не деплоил, займусь этим

2024-02-07 13:31 UTC, burtovoy requested changes
Сейчас не похоже на макет

2024-02-08 10:59 UTC, Agent007little commented
Доделал всю страницу, не получилось сделать горизонтальную линию между сообщениями, тег hr в HTML не отображается почему-то

2024-02-09 16:06 UTC, burtovoy commented
Всю страницу не нужно, давай оставим только то что нужно по заданию

2024-02-12 11:24 UTC, Agent007little commented
Переделал как смог, на созвоне обсудим детали.

2024-02-13 15:21 UTC, merged